
    create table calificacion_sugerencias (
        Id bigint generated by default as identity (start with 1),
        sensibilidadGlobal varchar(255),
        primary key (Id)
    )

    create table eventos (
        Id bigint generated by default as identity (start with 1),
        fechaFin varbinary(255),
        fechaInicio varbinary(255),
        frecuencia varchar(255),
        tipoEvento varchar(255),
        titulo varchar(255),
        usuario_id bigint,
        primary key (Id)
    )

    create table sugerencias (
        Id bigint generated by default as identity (start with 1),
        estado varchar(255),
        calificacion_Id bigint,
        usuario_id bigint,
        primary key (Id)
    )

    create table usuarios (
        Id bigint generated by default as identity (start with 1),
        mail varchar(255),
        nombre varchar(255),
        numeroTelefono varchar(255),
        primary key (Id)
    )

    alter table eventos 
        add constraint FK_qohe0ryp5s2vjersaktppdm4r 
        foreign key (usuario_id) 
        references usuarios

    alter table sugerencias 
        add constraint FK_48w7114fuoujhcqx3pophlw3o 
        foreign key (calificacion_Id) 
        references calificacion_sugerencias

    alter table sugerencias 
        add constraint FK_gxobpdcf0dy2cs6r8pr7cfud6 
        foreign key (usuario_id) 
        references usuarios
